version: "3"

services:
  haproxy:
    image: ifrscanoas/haproxy:latest
    ports:
      - "80:80"
      - "443:443"
      - "1936:1936"
    volumes:
      - vol-haproxy:/usr/local/etc/haproxy/:ro
  
  web1:
    image: tutum/hello-world

  web2:
    image: tutum/hello-world

  rsyslog:
    image: ifrscanoas/rsyslog
    volumes:
      - vol-haproxy-log:/var/log/:rw

volumes:
  vol-haproxy:
    external: true
  vol-haproxy-log:
    external: true

networks:
  default:
    external:
      name: net-web
